/**
 * Export shadcn project as ZIP file
 * Client-side only - uses browser APIs
 */

import JSZip from "jszip";
import { ShadcnExportResult } from "@proto-typed/core";

/**
 * Export shadcn project files as a ZIP download
 * Uses JSZip to create a zip file with all project files
 */
export async function exportShadcnProject(
  result: ShadcnExportResult,
  projectName: string = "proto-typed-export"
): Promise<void> {
  try {
    const zip = new JSZip();

    // Add all files to the zip
    result.files.forEach((file) => {
      zip.file(file.path, file.content);
    });

    // Add SETUP.md with installation instructions
    const setupInstructions = generateSetupInstructions(result);
    zip.file("SETUP.md", setupInstructions);

    // Generate the zip file
    const blob = await zip.generateAsync({ type: "blob" });

    // Trigger download
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `${projectName}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Clean up
    URL.revokeObjectURL(link.href);
  } catch (error) {
    console.error("Error exporting shadcn project:", error);
    throw new Error("Failed to export project. Please try again.");
  }
}

/**
 * Generate setup instructions
 */
function generateSetupInstructions(result: ShadcnExportResult): string {
  const requiredComponents = getRequiredShadcnComponentsFromFiles(result);

  return `# Setup Instructions

## 1. Install Dependencies

\`\`\`bash
npm install
\`\`\`

## 2. Initialize shadcn/ui

\`\`\`bash
npx shadcn@latest init
\`\`\`

When prompted, use these settings:
- Style: Default
- Base color: Zinc
- CSS variables: Yes

## 3. Install Required shadcn/ui Components

Install the following shadcn/ui components:

\`\`\`bash
${requiredComponents.map(comp => `npx shadcn@latest add ${comp.toLowerCase()}`).join("\n")}
\`\`\`

Or install all at once:

\`\`\`bash
npx shadcn@latest add ${requiredComponents.map(c => c.toLowerCase()).join(" ")}
\`\`\`

## 4. Install Additional Dependencies

Some components might need additional packages:

\`\`\`bash
npm install tailwindcss-animate
\`\`\`

## 5. Run Development Server

\`\`\`bash
npm run dev
\`\`\`

The application will be available at http://localhost:5173

## 6. Build for Production

\`\`\`bash
npm run build
\`\`\`

## Troubleshooting

### Module not found errors
If you encounter "Module not found" errors, make sure:
1. All dependencies are installed: \`npm install\`
2. All shadcn components are installed (see step 3)
3. The \`@/*\` path alias is configured in \`tsconfig.json\` and \`vite.config.ts\`

### Styling issues
If components don't look right:
1. Check that \`globals.css\` is imported in \`main.tsx\`
2. Verify Tailwind is configured correctly in \`tailwind.config.ts\`
3. Make sure \`postcss.config.js\` is present

### Type errors
Run \`npm run build\` to see all TypeScript errors. Most type errors can be fixed by:
1. Installing missing type definitions: \`npm install -D @types/react @types/react-dom\`
2. Updating TypeScript: \`npm install -D typescript@latest\`

## Project Structure

\`\`\`
proto-typed-export/
├── src/
│   ├── components/          # Screen components
│   │   └── ui/             # shadcn/ui components
│   ├── lib/                # Utilities
│   ├── App.tsx             # Main app with routing
│   ├── main.tsx            # Entry point
│   └── globals.css         # Global styles
├── package.json
├── tsconfig.json
├── tailwind.config.ts
├── vite.config.ts
└── index.html
\`\`\`

## Next Steps

After setup, you can:
1. Customize components in \`src/components/\`
2. Add new routes in \`src/App.tsx\`
3. Modify theme colors in \`src/globals.css\`
4. Install additional shadcn/ui components as needed

## Resources

- [shadcn/ui Documentation](https://ui.shadcn.com)
- [React Router Documentation](https://reactrouter.com)
- [Tailwind CSS Documentation](https://tailwindcss.com)
- [Vite Documentation](https://vitejs.dev)

---

Generated by proto-typed
`;
}

/**
 * Extract required shadcn components from generated files
 */
function getRequiredShadcnComponentsFromFiles(result: ShadcnExportResult): string[] {
  const components = new Set<string>();

  // Parse imports from component files
  result.files.forEach((file) => {
    if (file.path.startsWith("src/components/") && file.path.endsWith(".tsx")) {
      const importMatches = file.content.matchAll(/from ["']@\/components\/ui\/([^"']+)["']/g);
      for (const match of importMatches) {
        components.add(match[1]);
      }
    }
  });

  return Array.from(components).sort();
}

/**
 * Get list of required components for display before export
 */
export function getRequiredComponents(result: ShadcnExportResult): string[] {
  return getRequiredShadcnComponentsFromFiles(result);
}
